### ISSUE TITLE
read in deep image or catalog to identify sources on facet boundaries

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#10]
currently factor reads in the *merge files which contain clean components from 10subband images. It may be preferable if in the pre-factor pipeline we would make a deep ~200subband image (by regridding, smoothing and weighted average) and either read that image or a catalog from it into factor. This would pick up much more sources and would reduce the chance of sources laying on the facet boundaries.

**Comment by rvweeren** [comment]
I think it would be better to directly make a deep full bandwidth image with WSClean in prefactor to achieve this.  (also means for a full dataset we only have to run WSclean twice (one time for the high-resolution and one time for the low-resolution) for a full dataset. Instead of the ~30x we have to run it now. (see https://github.com/lofar-astron/prefactor/issues/7)

**Comment by rvweeren** [comment]
I think this is prefactor related (and for which Wendy already has a test version) so I close this.
