### ISSUE TITLE
pre-apply solutions from the brightest peeling selfcal solutions

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#113]
The solutions for the first peeling source are usually quite good (because S/N is high). It would be beneficial to "pre-apply" the phase component (TEC + CSphase + slow gain phase part) of these solutions to all other directions in the main FoV (not outliers facets). 

This should also remove the clock signal (+other offsets) from the data (as these are absorbed into the TEC/CSphase and slow phase solutions). This has several advantages:

(1) Would reduce the time interval needed to solve for TEC+CSphase somewhat (as we already take out part of the time variations of the phases, depending on how far one is away from the first peeling source)

(2) Then for all other directions we should be able to just fit for TEC+CSphase across the full bandwidth  (at the moment we still have a 0.5 rad phase component from the clock making this less optimal). Maybe even just only TEC. (still need to the slow gains of course for the beam effect)

**Comment by darafferty** [comment]
I've added this functionality to the master branch with commit 816ea13 (and will work now to port it to the wsclean branch). The new options preapply_first_cal_phases and preapply_solve_TEC_only under [calibration] control whether or not pre-application is done and if so, whether TEC or TEC+CSphase is solved for (see the example parset for details).

As Reinout described above, the phase solutions from the first calibrator are applied to subsequent ones, these getting only a single TEC or TEC+CSphase solution for the full bandwidth.  For the moment, the solution time intervals are the same as before, but it should be easy to scale them depending on the distance from the first calibrator.

**Comment by darafferty** [comment]
I've now also added the pre-apply options to the wsclean branch.

**Comment by twshimwell** [comment]
great. Sounds like a good feature. I guess this isn't tested much but any early hints as to whether this will produce better results (stability or quality).

**Comment by darafferty** [comment]
I've only tested it on 4 bands (with the TEC only option) and it seemed to work well, but obviously we need to test it on a much larger bandwidth. If it does work, it would result in a large reduction in the number of free parameters: we would go from two parameters (TEC+CSphase) per frequency block to just one or two over the whole bandwidth, so a reduction of a factor of ~ 4-8.

**Comment by darafferty** [comment]
I've now done a test with the full bandwidth (~ 40 MHz), using the wsclean branch. The pre-applied solutions were derived from peeling on 3C295 (5 MHz per TEC+CSphase block, 50 seconds per slow gain solution). I set preapply_solve_TEC_only = True, so no CSphase. The results look encouraging:

![screen shot 2016-09-15 at 10 10 48](https://cloud.githubusercontent.com/assets/5547918/18542927/a80a6624-7b2d-11e6-9b87-96f7d47c13b9.png)

However, there is some problem in the TEC-only solver. For example, here are the TEC phases for RS509:

<img width="1262" alt="screen shot 2016-09-15 at 10 10 39" src="https://cloud.githubusercontent.com/assets/5547918/18542948/c3fbddc2-7b2d-11e6-92bd-cc3226487f3c.png">

I think we can see the slow gains trying to compensate for the times when the TEC did not fit well:

<img width="1286" alt="screen shot 2016-09-15 at 10 20 42" src="https://cloud.githubusercontent.com/assets/5547918/18543035/189ce402-7b2e-11e6-8ad6-9bcd9ace5889.png">

I suppose this problem is related to the one we saw with the TEC+CSphase solver, but in that case, the discretization did not appear in the combined phase corrections.

**Comment by darafferty** [comment]
By the way, the source was ~ 2 degrees away from 3C295.

I am now testing preapply_solve_TEC_only = False on the above dataset. Hopefully this will fix the problem (at the expense of using twice the number of free parameters, but still a big reduction from the old way).

**Comment by darafferty** [comment]
Indeed, solving for TEC+CSphase seems to have fixed the discretization problem (this is a different calibrator than the one above but lies near it):

![screen shot 2016-09-16 at 10 55 24](https://cloud.githubusercontent.com/assets/5547918/18580505/56f49294-7bfc-11e6-9e07-9b7accbe5f22.png)

![screen shot 2016-09-16 at 10 55 57](https://cloud.githubusercontent.com/assets/5547918/18580508/5b97456c-7bfc-11e6-9775-de526cb304de.png)

**Comment by rvweeren** [comment]
Nice results. I guess an important factor is how good the "pre-applied" phase solutions were.

**Comment by darafferty** [comment]
Yeah, the above case is an ideal one, I suppose.

**Comment by rvweeren** [comment]
I've used it for a while and it seems to work.
