### ISSUE TITLE
pre-apply solutions slow gains in peeling selfcal cycle.

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#114]
We can obtain better TEC+CSphase solution if we have the option the pre-apply the slow gain solutions (when they become available) when solving for TEC+CSphase (so we already take out the beam effect and thus are able to improve the TEC+SCphase). 

We do not "smooth" on the slow phases now

 So we should only pre-apply the slow-gains if:
- the slow phases are good (no weird outliers, otherwise they would directly affect the TEC+SCphase fitting)

OR
-  if we can "smooth" / do outlier rejection on the slow phases (needs to be looked into, probably not very difficult, if we use the real/imag values)

**Comment by darafferty** [comment]
I've made a version of the smoothing script that also smooths the slow phases using the same algorithms used for the amplitudes (it's just a quick hack of the existing amplitude-smoothing script,  called factor/scripts/smooth_amps_phases_spline.py). It seems to work OK on one test dataset, due to the fact that the phases are always near zero and do not wrap. Do you think this will always be true, or do we need to handle cases in which the phases might wrap?

**Comment by rvweeren** [comment]
The phases usually do not wrap (expect maybe for outlier peeling sources, those which are really far out, i.e., 30 degr or so, but that's rare). BTW If you smooth on the real and imaginary parts you do not have the wrapping issue so I suggest to proceed that way.

**Comment by darafferty** [comment]
OK, I will work on doing the smoothing with the real/imag values.
