### ISSUE TITLE
Negative source holes in facetimage

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/factor#126]
Hi,

when I use CASA as facet imager, now strange negative sources appear in the facetimage step.
I marked them with red circles.
![negative_sources](https://cloud.githubusercontent.com/assets/19146990/17581833/5c7e562a-5fa8-11e6-829e-8f53460222f2.png)

Those negative sources appear in all (!) facet images. In some of them it seems to be kind of symmetric:

![negative_sources2](https://cloud.githubusercontent.com/assets/19146990/17581898/e3382c0e-5fa8-11e6-9ead-5c47aec2eb81.png)

I'm not really sure if anybody else is using CASA as facet imager, but couldn't this be something like aliasing?

**Comment by mhardcastle** [comment]
I used CASA (4.5) as the imager for a full run. I saw a little bit of aliasing of this sort; certainly not in every field though.

**Comment by mhardcastle** [comment]
(There is no real reason to suppose that CASA should be free of aliasing. Its default settings for aliasing protection are less conservative than what factor is now using for wsclean, IIRC. We have concentrated on dealing with the problem for wsclean partly because that's where we first found the problem and partly because it's easier to tune and more people are using it.)

**Comment by adrabent** [comment]
I just want to report it. It occures in the latest version, but did not occur in the factor versions from spring this year. But I cannot exclude that this is CASA related issue. Is anybody else using CASA as facet imager?

**Comment by mhardcastle** [comment]
What version of CASA are you running? Is this changed or unchanged from earlier this year?

**Comment by adrabent** [comment]
In both cases I have used CASA 4.5.

**Comment by duyhoang-astro** [comment]
@adrabent :  I'm using CASA (v4.5) as facet imager as well. Similar artifact like that in your first image is seen in one of my facet images. But it is outside of the facet source region.

![screenshot from 2016-08-17 10-54-51](https://cloud.githubusercontent.com/assets/11923709/17730689/373c95e0-646a-11e6-8c26-85ab1d09d1c4.png)

**Comment by rvweeren** [comment]
I never saw these artifacts in casapy 4.2, something must have changed since then.

**Comment by wndywllms** [comment]
Strangely, I just checked one of my **wsclean** facet images and was surprised to find a very similar artefact (to Duy's) within the facet region, see:
http://stri-cluster.herts.ac.uk/~wwilliams/factor/factor_wsclean1.png
or a larger version which shows also positive arcs to the north and south of this facet
http://stri-cluster.herts.ac.uk/~wwilliams/factor/factor_wsclean_full.png

I've imaged this before with casa 4.5 without this problem:
http://stri-cluster.herts.ac.uk/~wwilliams/factor/factor_casa1.png
The only other difference is in how the first direction (3C295, in an outlier field directly south of these artefacts) was handled -- selfcaled and subtracted in the wsclean case and peeled in the casa case.

(images are links because for some reason I can't seem to upload any images here...)

**Comment by darafferty** [comment]
Alexander: for the run with all the negative holes, did you use skip_facet_imaging = True? 

I suspect that we need to pad the model images made for small patches by a large factor (actually there is no padding at the moment, as casa is used for the predict for all patches and we only use padding with WSClean). This is consistent with Wendy's results, I think, because peeling is done with DPPP (no model image is made) but selfcal+subtraction is done using a patch-sized model image.

To address this issue, I'm trying a padding factor of 10 in the wsclean branch now, since many patches will be only ~500-1000 pixels across without padding. However, instead of using a padding factor (which results in a range of model image sizes depending on the facet size), would it not be better to instead pad all model images to a single size that's appropriate for the field?

**Comment by darafferty** [comment]
Actually, thinking about it some more, I guess using a padding factor should be fine after all, as it is the region near the model image edges that's most severely affected by aliasing, the size of which of course scales with the model size.

**Comment by darafferty** [comment]
Perhaps we should consider scaling the padding by the peak flux in the facet. Sources like 3C295 will presumably need more padding than typical facets to get any aliased artifacts below the noise.

**Comment by adrabent** [comment]
@darafferty Yes, I am using skip_facet_imaging = True. This happened during a test run. I have not yet rerun factor with the same parameters but with skip_facet_imaging = False

**Comment by darafferty** [comment]
I believe this issue (aliased sources) should no longer occur in the current master, as the predict is now done using DPPP. Reopen if it is still found to occur.
