### ISSUE TITLE
post-image.fits contains much brighter features than pre-image.fits

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#164]
I thought that in the facetselfcal step the *post-image.fits should contain fainter features than in *pre-image.fits for the sources in the facet that has been self calibrated if the calibration goes ok. However, even when the calibration looks reasonable it seems like the residuals of sources within the calibrated facet are sometimes a fair amount larger in the *post-image.fits. Verify subtract then sometimes fails because of the large residuals even though the calibration has gone ok. 

Ive attached a screenshot with an example. Where the top left is *pre-image.fits, top right is *post-image.fits and the bottom is the calibrated facet image. Not sure why this would be happening.

![screenshot from 2016-11-28 17-42-08](https://cloud.githubusercontent.com/assets/12065270/20677017/0e528328-b592-11e6-8fdb-8dc4d8f7c80f.png)

**Comment by darafferty** [comment]
Indeed, the post image should have lower residuals, although sometimes large-scale extended emission is not picked up during selfcal or in the facet image, leading to larger residuals in the post image (which is more sensitive to such emission). I'm working on a fix for this, but it doesn't look to be the problem here.

Perhaps there is some problem with the improved sky model. Which are the calibrator sources? I ask because the sky models for the calibrator sources are constructed from the selfcal images, whereas those of the non-calibrator sources are made from the facet images, so any difference in the quality of their subtraction might provide a clue as to what's going wrong. Also, how large are the residuals in the post image?

**Comment by wndywllms** [comment]
I've just seen a case where the flux in the post image looks roughly the same order as the ~7 Jy calibrator source so it seems as if nothing was subtracted...
Not sure if this is the same issue as I know the calibration did not go too well, but the facet image does not look terrible.

![xmm_3c63](https://cloud.githubusercontent.com/assets/2170761/20722567/ff47f232-b65e-11e6-85f9-8c04d1997cb1.png)
(limits are -0.1 1 for the pre/post images and -0.01 0.1 for the facet image on the bottom)

**Comment by darafferty** [comment]
I had a similar problem with peeling 3C295 (basically all its flux remained in the post image) and it turned out that, because the pipeline had failed and I had resumed it (after rolling back the state a few steps), makesourcedb was run again and added the sources twice to the sourcedb (since it already existed). Therefore, twice the flux was added back before the new model was subtracted. I've fixed this issue as of yesterday. Could this have happened with your run too?

**Comment by mooneyse** [comment]
Hi David, I ran into the issue and Tim has been helping me tackle it.

Attached is another screenshot from a different facet. They are on the same colour scale and there seems to be larger residuals at the calibrator and further from it. The maximum residual in the `pre-image.fits` is 14 mJy and the maximum in the `post-image.fits` is 28 mJy. The actual image itself though looks good.

![screenshot from 2016-11-30 10-52-42](https://cloud.githubusercontent.com/assets/20988307/20748366/2f0641c4-b6ee-11e6-9946-356655bdbf1e.png)

**Comment by twshimwell** [comment]
Just wondering if it could be related to bands used in the selfcal. Do the same nbands_selfcal_facet_image get imaged in the residual and the facet image? From the names in the facetselfcal_pipeline.parset it seems like just the middle band gets imaged in the residual.

**Comment by darafferty** [comment]
Yes, only the middle band is imaged for the pre/post steps, but the improved model is subtracted from all bands before that, so the post image should still improve relative to the pre one.

Perhaps it's worth checking the improved sky model of the middle band for problems? It should end with `*.combine_skymodels`.

**Comment by wndywllms** [comment]
@darafferty for my issue the double adding you described could have happened I think as we did restart after rolling back a few steps (all the way back to the sync as in https://github.com/lofar-astron/factor/issues/156). Will try again.

**Comment by mooneyse** [comment]
I had a quick look through the `*.combine_skymodels` but to my untrained eye everything looked in order. Is there anything specific I should look out for?

I cleared the directory and re-ran factor to see if that would solve the issue but it did not. It failed at the same facet and for the same reason. Bear in mind that this is for 40 (consecutive) subbands only so I am hoping that using the full dataset will solve the issue.

![failed_facet](https://cloud.githubusercontent.com/assets/20988307/20828342/5c00a1da-b877-11e6-8765-40da47fcc70f.png)

**Comment by rvweeren** [comment]
Would it be possible/useful to have to option in checkfactor to display the pre/post check images  (in ds9 for example)? (as they provide an important diagnostic) ?

**Comment by AHorneffer** [comment]
I believe this has been solved now with the changes that David applied after the discussion in #183 
If not, then please re-open.
