### ISSUE TITLE
Verifying facet run

### ISSUE THREAD

**Issue by duyhoang-astro** [lofar-astron/factor#199]
Hi,
Factor said that it has successfully finished one of the facets. The max residuals in the widefield images (*.wsclean_pre-image.fits and .wsclean_post-image.fits) actually decrease (from 0.03216 to 0.03197). However, the max residuals in the facet region significantly increase (from 0.01497 to 0.03197), as we can see in the images below.

*pre-residual facet region
![image](https://cloud.githubusercontent.com/assets/11923709/23711660/c357aa5a-0420-11e7-8f7c-74a85b24cff2.png)
*post-residual facet region
![image](https://cloud.githubusercontent.com/assets/11923709/23711692/ddefc168-0420-11e7-84e6-2bcae8ea762c.png)

I guess Factor checks for the max residuals in the whole widefield residual image (as the old facet scripts do). But in this case it seems not to work properly. An additional check is probably needed to compare max residuals within both the facet and the widefield images?

P/S: perhaps, a not related question to the thread: how can I undo this direction (as we do in the facet scripts)? I can leave this facet here, let factor run on other facets, then come back to this facet later.  The option -r RESET, --reset=RESET seems to both undo and rerun the facet.
Thanks! Duy

**Comment by AHorneffer** [comment]
To me it looks like some weaker sources were not subtracted, probably because they were not within the masked region. If that is indeed the case, then you could supply a region file to Factor with these sources in there.

If you just want to rest one direction, but not selfcal it again, then you can do it the following way:
1. re-run  factor with the `-r` option
1. stop it after the `facetsubrest` operation is done and before the following `faceselfcal` operation finishes. (Because  a `faceselfcal usually` takes quite some time this shouldn't be too hard.)
1. change the order of the directions in your directions file and move the direction, that you don't want to selfcal further down. 
1. re-start factor

**Comment by duyhoang-astro** [comment]
@AHorneffer: Thanks for the tips. I reseted the facet and will try this facet later when the residuals are improved.
