### ISSUE TITLE
blavg (time correlation) 

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#36]
David: Does blavg (time correlation) works on the full time range ? Or time chunk ?
(for a dataset that is continuous in time) 

(I see some weird solutions in the tec (at select times) and am trying to figure out what went wrong)

**Comment by darafferty** [comment]
It works on the full time range, unless you have large gaps between chunks (30 min or more). Basically, the time chunks are merged before the averaging is done and then split again after averaging. 

I wonder if you could have some over-smoothing? I intend to add options so that the user can control the averaging (i.e., the ionfactor and BL scaling), but at the moment the ionfactor is estimated internally from the direction-independent phase solutions (see find_ionfactor() in factor/scripts/pre_average_multi.py). Factor also scales the target ionfactor by the apparent flux, so that fainter sources get more averaging, but this has not been well tuned and could easily cause over-smoothing in the fainter sources. You can find the value it used in the facetselfcal logs (search for "ionfactor").

**Comment by rvweeren** [comment]
Does not look like over smoothing to me, maybe it is related to problems with the TEC fitting again (did not use the new TEC_block_MHz implementation for this run). I'll close this for now, as I want to experiment with TEC_block_MHz first.

**Comment by rvweeren** [comment]
Just checking again (in relation to the amplitude smoothing/outlier finding).

Does the blavg only affect the TEC+ScP fitting, or also the slow gains (amplitudes?)

Because for the amplitude smoothing (even the current code) we need to assume the amplitudes are uncorrelated in time. Otherwise we get in trouble with the statistics for finding outliers.

**Comment by darafferty** [comment]
Yes, the blavg only affects the TEC+ScP fitting (the MS files have a copy of both the smoothed and unsmoothed data and weights, and the column names are switched back and forth as needed).

**Comment by rvweeren** [comment]
Ok, great, thanks.
