### ISSUE TITLE
DDE selfcal images improvement (include mask)

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#37]
I uploaded some example code of how to make DDE selfcal images. Although checkfactor gives a nice overview, it does not show the masks and needs manual scaling. Example below. This should be useful to find out problems with the masking.

[code to produce nice DDE selfcal images, including the beam and mask (tweaked from my earlier prefactor example), with adjusted scaling and linewidths](https://github.com/tammojan/facet-calibration/blob/master/makeDDEselfcalimages.py)

![example image made my tweaked plotting code](https://cloud.githubusercontent.com/assets/3879473/14157083/8abc9f26-f697-11e5-9f27-50028d1bf5b3.png)

**Comment by darafferty** [comment]
Very nice!  I will change checkfactor to make these images instead of opening casaviewer. I can also add a step to the pipeline that saves them to disk after selfcal is complete.

**Comment by darafferty** [comment]
I've added APLpy plotting to the facetpeel branch. It should generate the png image above for each selfcal image once selfcal is complete (with the same scaling for all). I've also added these plots to checkfactor, which will display a minimal overview of all the selfcal images (instead of opening casaviewer as before). Once I'm sure it's working well, I'll merge it into the master branch.

**Comment by twshimwell** [comment]
I see this uses an estimate of the image noise for the colour scale. I wonder if it is worth instead hard coding something that depends on the integration time and bandwidth (and maybe declination). e.g. we expect say 150uJy/beam for 8hrs and 50MHz bandwidth at a declination of say 60deg. 

This is because if the image noise is used then an image that is actually bad may well get a colour scale that makes it look decent. Also, ideally we want all of our images (within reason) to have a noise level that depends on just the integration time and the bandwidth (and maybe declination).

**Comment by rvweeren** [comment]
Would it also be ok to just print the noise somewhere on the image ?
(the reason for making the images in the first place is to check that the masking, etc. goes fine, and that might become "harder" with hardcoded scaling.)

**Comment by twshimwell** [comment]
Yeh I think printing the noise somewhere on the image would do the job too. Hopefully users will know approximately what noise level and approximate fidelity they can expect for the data so the noise level should be sufficient

**Comment by darafferty** [comment]
I've added the noise used for scaling to the title of each plot (and the window of the checkfactor grid of plots). I've merged the facetpeel branch with master, so these are now available on the master branch.

**Comment by twshimwell** [comment]
I updated my factor this morning and I get an error in factor/scripts/make_selfcal_images.py which I suspect is related to this issue.

The error is 

2016-04-21 09:13:35 ERROR   node.para13.strw.leidenuniv.nl.python_plugin: 'FITSFigure' object has no attribute 'set_title'

Anyone else seen this error? I dont really understand it because aplpy figures should have a set_title. 

Perhaps it could be related to the lack of a .fits file being created for the L232875_SBgr000-10_uv.dppp.pre-cal_chunk11_124B363FAt_0g.casa_image42.image.tt0 file (there are .fits files created for all others, e.g. 02.image.tt0, 12.image.tt0... 42_iter7.image.tt0)

**Comment by twshimwell** [comment]
Actually seems like it was just the set_title call. If I comment out the two set_title bits in the make_selfcal_images.py then it works fine. My aplpy version is 0.9.12 so perhaps a newer one is required will update and see.

**Comment by darafferty** [comment]
Ah yes: from [aplpy](https://github.com/aplpy/aplpy/blob/master/CHANGES.rst):

```
0.9.13 (2014-10-04)
-------------------

    New features
    ~~~~~~~~~~~~

    - Added ``FITSFigure.set_title`` method that can be used to set the title
      of a figure. [#175]
```

I'll add this version to the dependencies list.
