### ISSUE TITLE
niter 1000000

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#45]
wsclean now goes all the way to 1.000.000 as it cannot reach the clean threshold.
(wasting a lot of processing time, I had to wait all day for it to finish, while wsclean normally runs for  an hr or less)

My threshold 0.0141998898233 was, but it never got below 0.02

I think it is better to lower niter to 150.000. If you need more than this, multiscale should(!) have been triggered in the first place. If multiscale is triggered, the max niter should be 60.000 or so for the facet imaging. It is not expected you need more, even for the most complicated fields (based on my A2256 experience, which needed about 20.000 with multiscale)

In this way, if there is a problem with reaching the threshold at least wsclean stops at a more reasonable point. Not wasting CPU time to reach a million.

I think the reason that it goes all the way to 1.000.000 is that my map noise varies enormously across the field (I have 3C295 in there with a lot of artifacts) and in that case clean has problem reaching the threshold as in some parts of the map the local noise/artifacts are above the threshold.

BTW At how many sigma was this threshold put ?

**Comment by darafferty** [comment]
Ah yes, I set nsigma to 1.0 some time ago because I found that wsclean was not cleaning deeply enough but forgot to revisit this setting (it's set to 2.0 for casapy clean). Which nsigma is best do you think?

As perhaps you've already seen, I've now set niter to scale with the square root of the number of bands (as was done for the full1 image, but 6 times higher). So, for a full bandwidth, you should have ~150.000 iterations max for wsclean and 60.000 for casapy. Do these look OK?

**Comment by rvweeren** [comment]
nisgma = 2 should be ok for constant noise, however, the noise is very often not constant and therefore I think the current nsigma=1 is ok. At least it is running ok now for my reduction (using wsclean). But why would it be different for casapy ? Should we not use the same niter both for wsclean and casapy? That does seem more logical to me. (I presume you're talking about the full facet imaging here…)

**Comment by darafferty** [comment]
Yeah, casapy and wsclean should have the same threshold. They got out of sync because I was experimenting with wsclean. I've set both to 1 sigma.

For niter, I was following the settings in [doDDE_v21](https://github.com/tammojan/facet-calibration/blob/master/doDDE_v21_a2256.py) which uses 2.5 times more iterations for wsclean. Not sure why that is, though.

**Comment by rvweeren** [comment]
I think I was experimenting with clean depth a bit on the A2256 field (because the emission is very complex). Since we used similar depth now we can close this.
