### ISSUE TITLE
Facet ordering

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#50]
The order in which facets are dealt with can be sub-optimal for getting rid of artefacts. For example, outlier facets can be selected which are then imaged only after all the main facets have been imaged. The easiest way to deal with this, other than clever algorithms, would seem to be a mandatory re-imaging step at the end.

**Comment by Joshuaalbert** [comment]
I also think the ordering is related to whether or not you should process in groupings. I have experimented with groupings calibrating the brightest first sequentially and then parallel calibrating less bright and further distance facets. I try to take to into consideration when I create the facets with my script. see my response to issue 51.
On 9 Apr 2016 10:19, Martin Hardcastle notifications@github.com wrote:The order in which facets are dealt with can be sub-optimal for getting rid of artefacts. For example, outlier facets can be selected which are then imaged only after all the main facets have been imaged. The easiest way to deal with this, other than clever algorithms, would seem to be a mandatory re-imaging step at the end.

**Comment by darafferty** [comment]
It would be fairly easy to deal with the outliers/patches first before the real facets, but of course sometimes the selfcal will go poorly if the outlier is on the faint side or near a bright source in a facet that hasn't been dealt with. There is currently a "reimage" option under the [directions] section of the parset that will reimage the facets, but it is set to False by default. Perhaps we should change it to True and warn people who are only processing a few facets (because they're only interested in their target, for example) to turn it off.

**Comment by mhardcastle** [comment]
Yes, for imaging the full field I think the default should be True.

**Comment by darafferty** [comment]
On the reimage branch, I've now set the default for the reimaging parameter (now named "reimage_selfcaled") to True and added a warning if it's activated and the user isn't imaging the full field. At worst, some people may waste a bit of time if they ignore this warning, but at least it will produce the best image by default now.

**Comment by mhardcastle** [comment]
A second run through of my field with the reimage options on gives much improved results. Closing this issue.
