### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#80]
I have seen a couple of people now encountering the "too many open files problem" which is fixed by setting ulimit -n to a larger value than the normal default (which is 1024 I think for most operating systems).

Would id be possible for factor to check the value and give a warning to the user if it is smaller than say some number ? (I've had several email conversations now about this subject with people running into this issue and if we throw a warning it might help these people to address this by themselves.

Something along the lines of:

"The number of open files allowed by the operating system is <>, this could results in a "Too many open files problem when running factor. This number can be increased with unlimit -n <some good number>."

**Comment by AHorneffer** [comment]
Error message is there.
On "local" clusters I raised the active limit to the maximum allowed to the user.
I think on other machines this wouldn't help because the scheduler logs into the systems from scratch and ignores the local settings. (AFAIK you need to change your .bashrc / .chsrc / .profile in that case.)

**Comment by rvweeren** [comment]
Thanks. Yes, there's not much we can do in factor about non-local clusters so we can close this.
