### ISSUE TITLE
dir_local can fill up on concat_averaged

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#82]
Trying multinode execution where dir_local gets used for intermediate files for NDPPP, and also trying full bandwidth, I find that the pipeline crashes because dir_local fills up. If I understand what's happening correctly NDPPP simply does some processing on a file from the work directory and puts the output in dir_local, which then gets rsync'ed back to the working directory. So this should probably work and may even give some kind of efficiency gain, but there is no real gain from running lots of NDPPPs in parallel since it's IO-bound. If I could restrict to a small number of NDPPPs running per node I would probably get round my problem without any significant performance loss. Is there an easy way of doing that? Otherwise of course I can simply remove dir_local from the pipeline parset...

**Comment by darafferty** [comment]
Ah, yes -- in Hamburg we have only 6 CPUs per node, so even though our scratch disks are small we haven't had this problem. It should be quite easy to add an option that limits the number of (non-inplace) DPPP jobs per node.

**Comment by mhardcastle** [comment]
Good! I haven't done much with the relevant bits of the code but if you could point me at the routines I would need to modify I could have a go at this if you want... or happy to leave it to you. But I can't do any more testing till this is solved.

**Comment by AHorneffer** [comment]
On the AH-experimental branch I had something set up so that io-intensive tasks don't run with "ncpu" processes, but with sqrt(ncpu) processes. If you want, then I can try to merge that into the reimage branch.

**Comment by AHorneffer** [comment]
Ah, looks clean enough, so I committed it to the reimage branch.
Martin: let us know if that is good enough.

**Comment by mhardcastle** [comment]
Thanks, I'll take a look. I'd suggest that this might want to be exposed as a parameter in general as the value you want depends on your hardware setup (e.g. Reinout's SSDs). But sqrt(ncpu) might be a good default.

**Comment by rvweeren** [comment]
Yes, I've no problem with running 20+ NDPPP in parallel.

**Comment by mhardcastle** [comment]
When I've checked that it works at all for me I'll add a parameter to the parset.

**Comment by AHorneffer** [comment]
Reinout: will it actually speed things up compared to 5 or so NDPPPs in parallel? (With each NDPPP process having "ncpu" maximum number of threads.)
I run Factor on a 8-disk RAID0, but when NDPPP is mostly just moving data around, then the 33 processes are just waiting for the disks.

**Comment by rvweeren** [comment]
For NDPPP processes that use the maximum number of threads I am simply CPU limited. (so more than 1 CPU per NDPPP processes). However, for simple NDPPP write/copy using 1 CPU I can easily run 20+ in parallel without seeing any slow-down due to I/O. (same for taql processes, a simple copy of columns can be run in parallel on all 24 cpus with 100% usage)

(The problem with RAID is that you are limited by the SATA controller, which is a major bottleneck)

**Comment by mhardcastle** [comment]
This number is now an option, <tt>nthread_io</tt>, in the <tt>[cluster]</tt> section, with the default remaining at sqrt(ncpu/npernode). I've tested it and it seems to work. Will close this, reopen if there are problems with the option...

**Comment by darafferty** [comment]
Martin, I changed this option to be the total number of IO-intensive processes per node (rather than per direction per node) to be consistent with the other cluster options (ncpu and wsclean_fmem). The scheduler then decides how to divide up this number depending on how many directions are to be run at once per node. This way should be more efficient, because even if you specify two or more directions per node, sometimes fewer will actually be run.

**Comment by mhardcastle** [comment]
Makes sense.
