### ISSUE TITLE
archiving and resumability (from the discussion during the telecon for the Tier-1 survey) 

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#89]
After a factor run has completed we needed to have the option to (1) "archive" the output products (2) allow the possibility for re-imaging runs on different machines (from these archived output products).

**Comment by darafferty** [comment]
We might consider making a few (backwards-incompatible) changes that would allow us to save a fair bit of space needed for the archiving.  For example, if we copy only the SUBTRACTED_DATA_ALL column when chunking the data and then update this column during processing (instead of making a SUBTRACTED_DATA_ALL_NEW column), we could reduce the number of data columns in the chunks from three (DATA, SUBTRACTED_DATA_ALL, and SUBTRACTED_DATA_ALL_NEW) to one (DATA). (This change would also save some space during processing, of course.) However, this would require that Factor makes copies of short MS files (from interleaved observations) instead of making sym links to them as it does now, but the archiving script could detect a run done the old way and update/copy the MS files to match the new scheme. 

The unarchiving script would need to edit the mapfiles to update the paths if they have changed (for different machine). We'd also need an option in Factor to skip the processing of the input files (which would be nice to have anyway).

**Comment by AHorneffer** [comment]
IIRC there were some problems with only copying the SUBTRACTED_DATA_ALL from the non-chunked input files, which is why we now again do a copy during chunking.

I would also prefer to have a real exporter (archiving script), that makes a copy of the needed data and only of the needed data, to a new directory. That way this directory can then be tar-ed up and put on an archive. IMHO it would also make it easier to do major changes to the directory structure of the factor work directory (if we ever want to do one) without having to worry about importing old projects, one would only have to write an importer (unarchiving script) that is compatible with the new directory structure.

As far as I can see, the required data is:
- MSs with the SUBTRACTED_DATA_ALL_NEW column
- the parmDBs with the calibration values for each facet
- the model images that were subtracted from each facet
- the directions file
- the `vertices_file` for each facet, or the region file if that is enough to remember where the facet boundary detoured around a source
- the input files that were referenced in the directions file (input skymodels, clean masks, etc.)
- the factor parset

Do we need to be able to re-start / continue a factor run from an exported archive, or only to be able to re-image?

**Comment by darafferty** [comment]
> IIRC there were some problems with only copying the SUBTRACTED_DATA_ALL from the non-chunked input files, which is why we now again do a copy during chunking.

It should work if we rename the column to DATA in the chunked files (but that would be incompatible with the sym-linked files if both are present).

Regarding the stuff to keep, it would be nice to archive all the images and plots as well, as they're fairly small and shouldn't increase the size of the archive very much.

**Comment by darafferty** [comment]
One reason to continue a run would be to do a second major cycle (not possible yet, but it's on the wish list).

**Comment by shulevski** [comment]
Can we add the beta "archiving" script which Tim wrote to the Factor repo? Then, we can start by what it already offers (I believe that it archives the images and plots) and build upon that...

**Comment by twshimwell** [comment]
Maybe for a first simple archiving we could just take the facet measurement sets that are needed for reimaging outside of factor plus some plots and images?

**Comment by darafferty** [comment]
I've added a basic script (`archivefactor`) that will copy the most important files, such as the calibrated data (it will also uncompress and concatenate these data in frequency), the images and plots, the selfcal sky models and solution tables, and the chunks (if desired).

**Comment by nudomarinero** [comment]
Great! Is it possible to resume factor with the archived data?

**Comment by darafferty** [comment]
No, not yet. There are still a few things that need to be added to the archive, and then we need another script to unarchive everything correctly.

**Comment by darafferty** [comment]
I've added the initial version of an unarchiving script (`unarchivefactor`) that allows one to resume a Factor run from a previously archived run. For this to work, the archive has to be made with the new version of `archivefactor` using the `-f` flag ("f" for "full"), which saves the subtracted-data files and all the mapfiles, etc. needed by Factor.

**Comment by darafferty** [comment]
During the busy week 26 last week, we tested the archive/unarchive sequence and it seems to work. Please reopen this issue if there are problems.
