### ISSUE TITLE
Parameter 'ncpu' not used?

### ISSUE THREAD

**Issue by sarrvesh** [lofar-astron/factor#92]
I am running factor (with the latest version) on cep with ncpu = 10 and wsclean_fmem = 0.8. I notice that factor is not using the set cpu limit. When I checked the cpu usage, I noticed that factor was running more than 10 BBS commands in parallel and the system load average was about 40. So is ncpu used only for wsclean runs?

**Comment by darafferty** [comment]
No, ncpu should be used for all steps so there should never be more than ncpu BBS jobs running at once. Can you check the pipeline.cfg file for the currently running operation (e.g., results/facetselfcal/facet_patch_342/pipeline.cfg)? The max_cpus_per_node value should be set to that of ncpu.

**Comment by darafferty** [comment]
Are you running more than one direction at a time? I just realized that in some cases (e.g., when running 4 directions at once with ncpus = 10) you can indeed use more than ncpu cores as the number each direction gets is calculated as int(round(ncpu_max / float(ndir_per_node))). This could be fixed by giving some directions fewer cores so that we don't exceed ncpu cores in total. (The inverse is also true -- in some cases fewer than ncpu cores will be used, such as with 3 directions with ncpu = 10 where each gets 3 cores).

**Comment by AHorneffer** [comment]
You could/should also check the tasks.cfg file that is referenced from the pipeline.cfg. That's where the max_cpus_per_node variable is used.

**Comment by rvweeren** [comment]
closed due to lack activity
