### ISSUE TITLE
Extended emission as calibrator source

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/factor#96]
Hi,

using extended sources as calibrator sources seems to be a rather complicated terrain.
In my case I had to use a selfdefined mask to properly get all the extended emission (see https://github.com/lofar-astron/factor/issues/94), otherwise pyBDSM is only masking the "hotspot".

![calibrator_field_199](https://cloud.githubusercontent.com/assets/19146990/15899961/e91688d8-2d9d-11e6-8fdd-698564c3e92f.png)

But still. The amplitudes are not calibrated well:
![facet_patch_199_amp](https://cloud.githubusercontent.com/assets/19146990/15899976/00dc623a-2d9e-11e6-9bda-67ada072e258.png)

Especially, the remote stations gone wild; probably because of missing flux.

What would be the solution?
- Implementing an option in the directions.txt which forbids the calibrator fields from using the highest resolution.. will this help?
- Simply avoiding extended sources as calibrators. But what if this source is really dominating your facet? Even if you have subtracted it very well in the beginning, could it cause problems then?

**Comment by AHorneffer** [comment]
Did you check how much flux there is on the long baselines?

Is there a compact source close the the extended one that you could include in your calibration? (And which has enough flux to calibrate the remote stations.)

And finally you could try to calibrate a compact source on only the long(er) baselines where the extended structure doesn't matter much.

**Comment by rvweeren** [comment]
As Andreas suggested, you simply do not have enough flux on the long baselines, nothing can be done about that.

 (you need some compact emission, try to extend the field for selfcal with more compact sources)

**Comment by adrabent** [comment]
I checked the facet and I think in my case this is rather complicated:
![situation](https://cloud.githubusercontent.com/assets/19146990/15922477/209e4ab8-2e28-11e6-8470-4d2f508f36f2.png)
We're talking about facet_patch_199.

To include an at least moderately bright source to the calibrator field, I would need to increase the size of the calibrator box in a way that it is overlapping with the neighbouring facet.

> And finally you could try to calibrate a compact source on only the long(er) baselines where the extended structure doesn't matter much.

How can this be realized within factor?

**Comment by twshimwell** [comment]
Ideally you want to have at least 0.5Jy of compact flux within the calibrator region. 

These calibrators for patch 199 and 210 are so close that i'd expect the solutions to be very similar and kind of remove the benefit of the independent calibration of these facets.

In factor you can define your own calibrator regions by giving it a directions file and in this case that is perhaps the simplest thing to do. So just take your directions file that it created for you and edit the facets you don't like (you can change the size and location of the calibrator regions) and then point to the new edited directions file in the parset with directions_file = newfile).

Alternatively, if you want to factor to automatically select the calibrators then id put a limit on how compact they need to be which can be done in the factor parset (by fiddling with size_max_arcmin and flux_min_Jy).

Once you make the edits then before doing much processing it is worth having a good look at the facet layout and calibrator regions that factor is using (overlay them on your source subtraction higher resolution images) prior to fully running factor so that you can tweak regions if necessary.

**Comment by adrabent** [comment]
Avoiding such a situation might be the smartest way.
But changing the direction of a calibrator source will allow factor to readjust all the facet boundaries.
This would mean that I have to rerun factor completely.

The biggest issue of my field is that (according to my directions.txt) only
2 sources > 1 Jy
5 sources > 0.5 Jy and < 1.0 Jy
14 sources > 0.3 Jy and < 0.5 Jy

The choice is therefore limited.

**Comment by AHorneffer** [comment]
> > ```
> > And finally you could try to calibrate a compact source on only the long(er) baselines where the extended structure doesn't matter much.
> > ```
> 
> How can this be realized within factor?

E.g. with this option:

```
# Minimum uv distance in lambda for calibration (default = 80.0)
# solve_min_uv_lambda = 80.0
```

I haven't tested it myself though.

But in your case I would do as Tim suggests and just remove patch 199 from the list of facets.

**Comment by AHorneffer** [comment]
> This would mean that I have to rerun factor completely.

Then don't do selfcal for facet 199, but just use the solutions from the nearest facet:
- sort the directions file so that patch 199 is at the end of the list of processed directions
- set `ndir_selfcal` to a value smaller than the position of patch 199 in the directions file
